# Generated by Django 3.2.9 on 2022-01-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_readed',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
    ]
