# Generated by Django 3.2.9 on 2021-12-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publiсation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('full_text', models.TextField(verbose_name='Публикация')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('author', models.IntegerField(verbose_name='Автор')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
        ),
    ]
