# Generated by Django 3.2.9 on 2021-12-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publiсation',
            options={'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.RemoveField(
            model_name='publiсation',
            name='image',
        ),
        migrations.AddField(
            model_name='publiсation',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='images/post/', verbose_name='Изображение поста'),
        ),
        migrations.AddField(
            model_name='publiсation',
            name='post_image_url',
            field=models.ImageField(blank=True, upload_to='', verbose_name='URL изображения поста'),
        ),
        migrations.AlterField(
            model_name='publiсation',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
