# Generated by Django 3.2.9 on 2021-12-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20211208_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publiсation',
            name='full_text',
            field=models.TextField(verbose_name='Текст публикации'),
        ),
    ]
