# Generated by Django 3.2.9 on 2021-12-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_publiсation_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publiсation',
            name='author',
            field=models.IntegerField(verbose_name='Автор'),
        ),
    ]
