# Generated by Django 3.2.9 on 2022-01-05 06:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0006_alter_publiсation_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publiсation',
            new_name='Publication',
        ),
    ]
