# Generated by Django 3.2.9 on 2021-12-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.ImageField(blank=True, upload_to='', verbose_name='URL аватара пользователя'),
        ),
    ]
