# Generated by Django 3.2.9 on 2022-01-03 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='confirmed',
        ),
    ]
