# Generated by Django 3.2.9 on 2022-01-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_contact_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Статус'),
        ),
    ]
