# Generated by Django 3.2.9 on 2022-01-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='new_field',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
    ]
